name: Despliegue prueba Pages

on:
  push:
    branches: 
    - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar Pruebas Unitarias
        run: npm run test
        
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias para JSDoc
        run: npm install

      - name: Generar Documentación JSDoc
        run: npm run docs

      - name: Mover y Unificar Archivos de Despliegue
        run: |
          # 2a. Crea una carpeta temporal, 'page_root', para el despliegue final
          mkdir page_root
          
          # 2b. Copia todos los archivos de tu carpeta 'src/' (index.html, styles, etc.) a la raíz de la página
          # El -R copia recursivamente todo el contenido, manteniendo la estructura de carpetas
          cp -R src/* page_root/
          
          # 2c. Mueve la carpeta de documentación JSDoc generada dentro de 'page_root'
          # La documentación será accesible en URL/docs/
          mv docs page_root/docs/

          echo "pruebapages.frandaw.com" > page_root/CNAME 
          
          mv docs page_root/docs/
          
      - name: Desplegar a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./page_root