name: Despliegue prueba Pages

on:
  push:
    branches: 
    - develop

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Instalar dependencias
        run: npm install
      - name: Ejecutar Pruebas Unitarias
        run: npm run test
        
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4
        
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias para JSDoc
        run: npm install

      - name: Generar Documentación JSDoc
        run: npm run docs

      - name: Desplegar Documentación a GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs